services:
  oracledbtest:
    image: container-registry.oracle.com/database/express
    container_name: Oracle_Storage_Test_backup_recover
    environment:
      ORACLE_PWD: "systemtest123"
      ORACLE_CHARACTERSET: "AL32UTF8"
    ports:
      - "1541:1521"
      - "5540:5500"
    volumes:
          - ./script_db_backup_recovery.sql:/tmp/script_db_backup_recovery.sql
          - ./backup:/opt/oracle/oradata/dpump
    restart: unless-stopped
