CREATE USER C##BOT_RPA IDENTIFIED BY botrpa;
GRANT CONNECT TO C##BOT_RPA;
ALTER USER C##BOT_RPA QUOTA UNLIMITED ON USERS;

ALTER USER SYSTEM IDENTIFIED BY "newPassword123";

CREATE TABLE "C##BOT_RPA"."STATUS_LOG"
(
    "STATUS_ID" CHAR(1) NOT NULL, 
    "STATUS_NAME" VARCHAR2(50) NOT NULL, 
    "STATUS_DESC" VARCHAR2(250) NULL, 
    CONSTRAINT "PK_STATUS_LOG" PRIMARY KEY ("STATUS_ID")
);

CREATE TABLE "C##BOT_RPA"."ACCOUNT_TYPE"
(
    "ACC_TYPE_CODE" CHAR(2) NOT NULL,  
    "ACC_TYPE_NAME" VARCHAR2(255) NOT NULL, 
    CONSTRAINT "PK_ACC_TYPE_CODE" PRIMARY KEY ("ACC_TYPE_CODE")
);

CREATE TABLE "C##BOT_RPA"."TRANSACTION_CHANNEL"
(
    "TRX_CHNL_CODE" CHAR(2) NOT NULL,  
    "TRX_CHNL_NAME" VARCHAR2(255) NOT NULL, 
    "TRX_CHNL_DESC" VARCHAR2(255), 
    CONSTRAINT "PK_TRX_CHNL_CODE" PRIMARY KEY ("TRX_CHNL_CODE")
);

CREATE TABLE "C##BOT_RPA"."DOC_TYPE"
(
    "DOC_TYPE_CODE" CHAR(1) NOT NULL,  
    "DOC_TYPE_NAME" VARCHAR2(255) NOT NULL, 
    CONSTRAINT "PK_DOC_TYPE_CODE" PRIMARY KEY ("DOC_TYPE_CODE")
);

CREATE TABLE "C##BOT_RPA"."PROCESS_LOG"
(
    "PROCESS_LOG_SEQ" NUMBER GENERATED ALWAYS AS IDENTITY NOT NULL,  
    "PROCESS_LOG_NAME" VARCHAR2(100) NOT NULL, 
    "PROCESS_LOG_DESC" VARCHAR2(255), 
    "PROCESS_LOG_CREATED_BY" VARCHAR2(100) NOT NULL, 
    "PROCESS_LOG_TIMESTAMP" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "PK_PROCESS_LOG_SEQ" PRIMARY KEY ("PROCESS_LOG_SEQ")
);

CREATE TABLE "C##BOT_RPA"."SUB_PROCESS_LOG"
(
    "STEP_LOG_SEQ" NUMBER GENERATED ALWAYS AS IDENTITY NOT NULL, 
    "STEP_NAME" VARCHAR2(100) NOT NULL, 
    "DOC_NAME" VARCHAR2(150) NULL, 
    "ISSUE_DATE" CHAR(8) NULL, 
    "AGENT_CODE" CHAR(4) NULL, 
    "VERSION" VARCHAR2(5) NULL,
    "ACC_TYPE_CODE" CHAR(2) NULL,
    "TRX_CHNL_CODE" CHAR(2) NULL,
    "TRANSACTION_ID" CHAR(6) NULL,
    "STATUS_ID" CHAR(1) NOT NULL, 
    "PROCESS_LOG_SEQ" NUMBER NOT NULL,
    "STEP_LOG_DESC" VARCHAR2(255), 
    "STEP_CREATED_BY" VARCHAR2(100) NOT NULL, 
    "STEP_LOG_TIMESTAMP" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "PK_SUB_PROCESS_LOG" PRIMARY KEY ("STEP_LOG_SEQ"),
    CONSTRAINT "FK_SUB_PROCESS_LOG" FOREIGN KEY ("PROCESS_LOG_SEQ")
        REFERENCES "C##BOT_RPA"."PROCESS_LOG" ("PROCESS_LOG_SEQ"),
    CONSTRAINT "FK_SUB_PROCESS_LOG_STATUS" FOREIGN KEY ("STATUS_ID")
        REFERENCES "C##BOT_RPA"."STATUS_LOG" ("STATUS_ID"),
    CONSTRAINT "FK_SUB_PROCESS_LOG_ACC_TYPE" FOREIGN KEY ("ACC_TYPE_CODE")
        REFERENCES "C##BOT_RPA"."ACCOUNT_TYPE" ("ACC_TYPE_CODE"),
    CONSTRAINT "FK_SUB_PROCESS_LOG_TRX_CHNL" FOREIGN KEY ("TRX_CHNL_CODE")
        REFERENCES "C##BOT_RPA"."TRANSACTION_CHANNEL" ("TRX_CHNL_CODE")
);

-- Create Index for DOC_NAME
CREATE INDEX IDX_SUB_PROCESS_LOG_DOC_NAME 
ON C##BOT_RPA.SUB_PROCESS_LOG (DOC_NAME);

-- Grant privileges
GRANT SELECT, INSERT, UPDATE, DELETE ON C##BOT_RPA.PROCESS_LOG TO C##BOT_RPA;
GRANT SELECT, INSERT, UPDATE, DELETE ON C##BOT_RPA.SUB_PROCESS_LOG TO C##BOT_RPA;
GRANT SELECT, INSERT, UPDATE, DELETE ON C##BOT_RPA.STATUS_LOG TO C##BOT_RPA;
GRANT SELECT, INSERT, UPDATE, DELETE ON C##BOT_RPA.ACCOUNT_TYPE TO C##BOT_RPA;
GRANT SELECT, INSERT, UPDATE, DELETE ON C##BOT_RPA.TRANSACTION_CHANNEL TO C##BOT_RPA;
GRANT SELECT, INSERT, UPDATE, DELETE ON C##BOT_RPA.DOC_TYPE TO C##BOT_RPA;
GRANT DBA TO C##BOT_RPA;

-- Set Auto Commit Off
SET AUTOCOMMIT OFF;
